---
- hosts: all
  vars: 
    createuser: 'vagrant'
    createpassword: 'vagrant'
  tasks:
    #- name: Setup | create user
    #  command: useradd -m {{ createuser }} creates=/home/{{ createuser }}
   
    #- name: Setup | set user password
    #  shell: usermod -p $(echo '{{ createpassword }}' | openssl passwd -1 -stdin) {{ createuser }}
  
    - name: Setup | ssh key
      shell: ssh-keygen -t rsa -P "" -f /home/{{ createuser }}/.ssh/id_rsa
  
    - name: Setup | authorized key upload
      authorized_key: user={{ createuser }}
        key="{{ lookup('file', '/home/{{ createuser }}/.ssh/id_rsa.pub') }}"
        path='/home/{{ createuser }}/.ssh/authorized_keys'
        manage_dir=no

    #- name: Sudoers | update sudoers file and validate
    #  lineinfile: "dest=/etc/sudoers
    #    insertafter=EOF
    #    line='{{ createuser }} ALL=(ALL) NOPASSWD: ALL'
    #    regexp='{{ createuser }} ALL=(ALL) NOPASSWD: ALL'
    #    state=present"
  
    #- name: ensure ntpd is at the latest version
    #  become: yes
    #  apt: name=ntp update-cache=yes
    #  notify:
    #  - restart ntpd
#  handlers:
#    - name: restart ntpd
#      service: name=ntpd state=restarted